/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f4xx.h"
#include "gpio_driver_hal.h"
#include "timer_driver_hal.h"

// Definimos un pin de prueba
// Definimos un pin de prueba
GPIO_Handler_t userLed = {0};   // Pin A5
GPIO_Handler_t userBoton = {0}; // Pin C13
Timer_Handler_t reloj1 = {0};
uint8_t btnValue = 0;       // Valor leído del botón
uint8_t lastBtnState = 0;   // Estado previo del botón
uint8_t upStateInit = 1; // estado inicial alto
void init_Config(void);
int main(void){

	init_Config();

    while (1)
    {
        btnValue = gpio_ReadPin(&userBoton);

        // Detectamos un cambio de estado en el botón (flanco ascendente)
        if (btnValue == 1 && lastBtnState == 0)
        {
			reloj1.TIMx_Config.TIMx_Period = 50;
            timer_SetState(&reloj1, TIMER_OFF);
            timer_Config(&reloj1);
            timer_SetState(&reloj1, TIMER_ON);
            lastBtnState = btnValue;
        }
    }
}

// Callback del temporizador
void Timer5_Callback(void)
{
    gpio_TooglePin(&userLed); // Alterna el estado del LED
}
void init_Config(void)
{
	userLed.pGPIOx = GPIOA;
	userLed.pinConfig.GPIO_PinNumber = PIN_5;
	userLed.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	userLed.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	userLed.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&userLed);

	// Configuramos el pin del botón
	userBoton.pGPIOx = GPIOC;
	userBoton.pinConfig.GPIO_PinNumber = PIN_13;
	userBoton.pinConfig.GPIO_PinMode = GPIO_MODE_IN;
	userBoton.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&userBoton);

	// Configuramos el temporizador
	reloj1.pTIMx = TIM5;
	reloj1.TIMx_Config.TIMx_Prescaler = 16000; // Genera incrementos de 1 ms
	reloj1.TIMx_Config.TIMx_Period = 250;      // LED parpadea cada 250 ms
	reloj1.TIMx_Config.TIMx_mode = TIMER_UP_COUNTER;
	reloj1.TIMx_Config.TIMx_InterruptEnable = TIMER_INT_ENABLE;
	timer_Config(&reloj1);

	// Encendemos el temporizador
	timer_SetState(&reloj1, TIMER_ON);
}
