/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f4xx.h"
#include "stm32_assert.h"
#include "gpio_driver_hal.h"
#include "timer_driver_hal.h"

// definimos  un pin de prueba
GPIO_Handler_t userLed = {0}; //pinA5

Timer_Handler_t blinkTimer = {0};

/*
 * The main funct, where ..
 */
int main(void)
{
    /* Configuramos el pin */
	userLed.pGPIOx			 				=GPIOA;
	userLed.pinConfig.GPIO_PinNumber 		=PIN_5;
	userLed.pinConfig.GPIO_PinMode			=GPIO_MODE_OUT;
	userLed.pinConfig.GPIO_PinOutputType	=GPIO_OTYPE_PUSHPULL;
	userLed.pinConfig.GPIO_PinOutputSpeed	=GPIO_OSPEED_MEDIUM;
	userLed.pinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;

	/* cargamos la configuracion de los registros que gobiernan el puerto */
	gpio_Config(&userLed);

	gpio_WritePin(&userLed, SET);

	blinkTimer.pTIMx							=TIM2;
	blinkTimer.TIMx_Config.TIMx_Prescaler		=16000; // genera incrementos de 1ms
	blinkTimer.TIMx_Config.TIMx_Period			=250;	//de la mano con el prescaler,
	blinkTimer.TIMx_Config.TIMx_mode			=TIMER_UP_COUNTER;
	blinkTimer.TIMx_Config.TIMx_InterruptEnable	=TIMER_INT_ENABLE;

	/* CONFIGURAMOS EL timer */
	timer_Config(&blinkTimer);

	//Encedemos el Timer
	timer_SetState(&blinkTimer, TIMER_ON);

	while(1){


	}
}


/*
 * overwrite function
 * */
void Timer2_Callback(void){
	gpio_TooglePin(&userLed);
}

/*
 * Esta funcion sirve para  detectar problemas de parametros
 * incorrectos al momento d eejecutar un programa
 */
void assert_failed(uint8_t* file, uint32_t line){
	while(1){
		//problems
	}
}
