/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f4xx.h"
#include "stm32_assert.h"
#include "gpio_driver_hal.h"
#include "timer_driver_hal.h"

// definimos  un pin de prueba
GPIO_Handler_t userLed = {0}; //pinA5
GPIO_Handler_t userBoton = {0}; //pinA5
Timer_Handler_t blinkTimer = {0};
Timer_Handler_t reloj1={0};
uint8_t btnValue=0; 	//variable que lee el dato que viene del boton
/*
 * The main funct, where ..
 */
int main(void)
{
    /* Configuramos el pin */
	userLed.pGPIOx			 				=GPIOA;
	userLed.pinConfig.GPIO_PinNumber 		=PIN_5;
	userLed.pinConfig.GPIO_PinMode			=GPIO_MODE_OUT;
	userLed.pinConfig.GPIO_PinOutputType	=GPIO_OTYPE_PUSHPULL;
	userLed.pinConfig.GPIO_PinOutputSpeed	=GPIO_OSPEED_MEDIUM;
	userLed.pinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;

	/* cargamos la configuracion de los registros que gobiernan el puerto */
	gpio_Config(&userLed);

	gpio_WritePin(&userLed, SET);

    /* configuramos el pin */
	userBoton.pGPIOx			 				=GPIOA;
	userBoton.pinConfig.GPIO_PinNumber 			=PIN_13;
	userBoton.pinConfig.GPIO_PinMode			=GPIO_MODE_IN;
	userBoton.pinConfig.GPIO_PinPuPdControl		= GPIO_PUPDR_NOTHING;

	/* cargamos la configuracion de los registros que gobiernan el puerto */
	gpio_Config(&userBoton);


	//160000 solo por que el micro va a 16MHz. conversion 1 a 1 en el prescaler.

	reloj1.pTIMx							=TIM2;
	reloj1.TIMx_Config.TIMx_Prescaler		=16000000; // genera incrementos de 1ms  //sería lo mismo si: //250
	reloj1.TIMx_Config.TIMx_Period			=1;	//de la mano con el prescaler,						//16000
	reloj1.TIMx_Config.TIMx_mode			=TIMER_UP_COUNTER;
	reloj1.TIMx_Config.TIMx_InterruptEnable	=TIMER_INT_ENABLE;

	/* CONFIGURAMOS EL timer */
	timer_Config(&reloj1);

	//Encedemos el Timer
	timer_SetState(&reloj1, TIMER_ON);

	while(1){
		btnValue=gpio_ReadPin(&userBoton);

		if(btnValue){
			reloj1.TIMx_Config.TIMx_Period = 1000;
			timer_SetState(&reloj1,TIMER_OFF);
			timer_Config(&reloj1);
			timer_SetState(&reloj1,TIMER_OFF);


		}


	}
}


/*
 * overwrite function
 * */
void Timer2_Callback(void){
	gpio_TooglePin(&userLed);
}

/*
 * Esta funcion sirve para  detectar problemas de parametros
 * incorrectos al momento d eejecutar un programa
 */
void assert_failed(uint8_t* file, uint32_t line){
	while(1){
		//problems
	}
}
